AllCops:
  DisplayStyleGuide: true
  Exclude:
    - 'Gemfile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

