AllCops:
  DisplayStyleGuide: true
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

